In [3]:
with open('Two.txt') as textone:
    print(textone.read())

This story is about surfing
Catching waves is fun
Surfing is a popular water sport



In [5]:
#As a lise
with open('One.txt') as f_one:
    lines = f_one.readlines()

In [6]:
lines

['This is a story about dogs\n',
 'our canine pets\n',
 'Dogs are furry animals\n']

In [7]:
with open('One.txt') as textone:
    one_text = textone.read()

In [8]:
one_text

'This is a story about dogs\nour canine pets\nDogs are furry animals\n'

#### Creating a 'Bag of Words'

In [12]:
words_one = one_text.lower().split()

In [14]:
unique_words_one = set(words_one)
unique_words_one

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [16]:
with open('Two.txt') as texttwo:
    words_two = texttwo.read().lower().split()

In [17]:
words_two

['this',
 'story',
 'is',
 'about',
 'surfing',
 'catching',
 'waves',
 'is',
 'fun',
 'surfing',
 'is',
 'a',
 'popular',
 'water',
 'sport']

In [18]:
unique_words_two = set(words_two)
unique_words_two

{'a',
 'about',
 'catching',
 'fun',
 'is',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [19]:
all_unique_words = set()
all_unique_words.update(unique_words_one)
all_unique_words.update(unique_words_two)

In [20]:
all_unique_words

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [21]:
vocab_complete = dict()
i = 0

for w in all_unique_words:
    vocab_complete[w] = i
    i = i + 1

In [22]:
vocab_complete

{'popular': 0,
 'story': 1,
 'pets': 2,
 'furry': 3,
 'is': 4,
 'our': 5,
 'this': 6,
 'a': 7,
 'fun': 8,
 'water': 9,
 'canine': 10,
 'surfing': 11,
 'waves': 12,
 'are': 13,
 'catching': 14,
 'dogs': 15,
 'animals': 16,
 'sport': 17,
 'about': 18}

### Frequency Counts

In [23]:
one_freq = [0]*len(vocab_complete)
two_freq = [0]*len(vocab_complete)
all_words = ['']*len(vocab_complete)

In [24]:
one_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [25]:
two_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [26]:
all_words

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [27]:
for w in vocab_complete:
    w_ind = vocab_complete[w]
    all_words[w_ind]= w

In [28]:
all_words

['popular',
 'story',
 'pets',
 'furry',
 'is',
 'our',
 'this',
 'a',
 'fun',
 'water',
 'canine',
 'surfing',
 'waves',
 'are',
 'catching',
 'dogs',
 'animals',
 'sport',
 'about']

In [29]:
one_text

'This is a story about dogs\nour canine pets\nDogs are furry animals\n'

In [30]:
#add count for each word in each doc

for w in one_text.lower().split():
    w_ind = vocab_complete[w]
    one_freq[w_ind] = one_freq[w_ind] + 1

In [31]:
one_freq

[0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 2, 1, 0, 1]

In [33]:

for w in words_two:
    w_ind = vocab_complete[w]
    two_freq[w_ind] = two_freq[w_ind] + 1

In [35]:
words_two

['this',
 'story',
 'is',
 'about',
 'surfing',
 'catching',
 'waves',
 'is',
 'fun',
 'surfing',
 'is',
 'a',
 'popular',
 'water',
 'sport']

In [34]:
two_freq

[1, 1, 0, 0, 3, 0, 1, 1, 1, 1, 0, 2, 1, 0, 1, 0, 0, 1, 1]

In [36]:
import pandas as pd
pd.DataFrame(data=[one_freq,two_freq],columns=all_words)

popular  story  pets  furry  is  ...  catching  dogs  animals  sport  about
0        0      1     1      1   1  ...         0     2        1      0      1
1        1      1     0      0   3  ...         1     0        0      1      1

[2 rows x 19 columns]

## Feature Extraction with sklearn

In [37]:
txt1 = ['This is a line',
       'This is another line',
       'New  different line']

In [38]:
from sklearn.feature_extraction.text import TfidfTransformer, TfidfVectorizer, CountVectorizer

In [41]:
cv = CountVectorizer()
sparse_mat = cv.fit_transform(txt1)

In [42]:
sparse_mat.todense()

matrix([[0, 0, 1, 1, 0, 1],
        [1, 0, 1, 1, 0, 1],
        [0, 1, 0, 1, 1, 0]])

In [43]:
cv.vocabulary_

{'this': 5, 'is': 2, 'line': 3, 'another': 0, 'new': 4, 'different': 1}

In [44]:
cv = CountVectorizer(stop_words='english')
cv.fit_transform(txt1).todense()

matrix([[0, 1, 0],
        [0, 1, 0],
        [1, 1, 1]])

In [45]:
cv.vocabulary_

{'line': 1, 'new': 2, 'different': 0}

### Tfidf Transformer

In [46]:
tfidf_transformer = TfidfTransformer()

In [47]:
cv = CountVectorizer()
counts = cv.fit_transform(txt1)
counts

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [48]:
tfidf = tfidf_transformer.fit_transform(counts)
tfidf.todense()

matrix([[0.        , 0.        , 0.61980538, 0.48133417, 0.        ,
         0.61980538],
        [0.63174505, 0.        , 0.4804584 , 0.37311881, 0.        ,
         0.4804584 ],
        [0.        , 0.65249088, 0.        , 0.38537163, 0.65249088,
         0.        ]])

##### tfidf Vectorizer (to do the two steps in one go)

In [49]:
tfidf = TfidfVectorizer()
new_tfidf = tfidf.fit_transform(txt1)
new_tfidf.todense()

matrix([[0.        , 0.        , 0.61980538, 0.48133417, 0.        ,
         0.61980538],
        [0.63174505, 0.        , 0.4804584 , 0.37311881, 0.        ,
         0.4804584 ],
        [0.        , 0.65249088, 0.        , 0.38537163, 0.65249088,
         0.        ]])