In [1]:
import numpy as np

In [4]:
arr = np.arange(0,21,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr[4]

8

In [7]:
arr[:7]

array([ 0,  2,  4,  6,  8, 10, 12])

## Broadcasting

In [12]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18,  20])

In [14]:
slice_of_arr = arr[0:5]
slice_of_arr

array([100, 100, 100, 100, 100])

In [15]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99, 10, 12, 14, 16, 18, 20])

## data is not copied. Its a view of original array. This avoids memory problems

In [17]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 10, 12, 14, 16, 18, 20])

## Indexing a 2D array (Matrices)

In [18]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
arr_2d[1][1]

25

In [21]:
arr_2d[2][2]

45

In [22]:
arr_2d[2][-1]

45

In [23]:
arr_2d[-1][-1]

45

In [25]:
arr_2d[-1,-1]

45

In [27]:
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [36]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

## Conditional selection

In [37]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
bool_arr = arr > 4

In [39]:
arr[bool_arr == False]

array([1, 2, 3, 4])

In [40]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [41]:
arr[arr > 7]

array([ 8,  9, 10])

In [42]:
x = 10/5
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])