In [2]:
import numpy as np

In [3]:
#Create an array of 20 lineraly spaced points between 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [6]:
#reshape above array in 4*5 dimension
arr = np.linspace(0,1,20).reshape(4,5)

In [7]:
arr.sum(axis=1)

array([0.52631579, 1.84210526, 3.15789474, 4.47368421])

In [8]:
#left bottom 3*3
arr[1:,:3]

array([[0.26315789, 0.31578947, 0.36842105],
       [0.52631579, 0.57894737, 0.63157895],
       [0.78947368, 0.84210526, 0.89473684]])